server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ThanujaDissanayake/rentacar-config-store
          search-paths:
          - 'service-config/*service'
                 
#server.port= 8191
#spring.cloud.config.server.git.uri=https://github.com/ThanujaDissanayake/rentacar-config-store
#spring.cloud.config.server.git.search-paths==-'*service'
